# Jupyter Keyboard Shortcuts


`Shift + Enter` will run the cell
`Alt + Enter` runs the cell and opens a new coding block beneath it

`Esc + M` convert the block to Markdown block
`Esc + Y` convert the block to Code block

`Shift + Tab` gives the documentation of a function

In [5]:
import numpy as np

np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.arange(0,11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [7]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [8]:
np.zeros((5,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [9]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [10]:
np.ones((5,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [11]:
np.linspace(0,10,10)

array([  0.        ,   1.11111111,   2.22222222,   3.33333333,
         4.44444444,   5.55555556,   6.66666667,   7.77777778,
         8.88888889,  10.        ])

## Create an Identity Matrix

In [12]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Random Numbers

- `rand` - _uniform_ distribution between 0 and 1
- `randn` - _normal_ distribution; default mean = 0, sd = 1
- `randint` - returns random integers between defined low and high number

In [13]:
np.random.rand(5) # array of numbers in uniform distro from 0 to 1

array([ 0.11795945,  0.0886755 ,  0.74711473,  0.4907512 ,  0.43498426])

In [14]:
np.random.rand(5,3)

array([[ 0.83734209,  0.57182714,  0.90647566],
       [ 0.77841783,  0.00105924,  0.40852462],
       [ 0.53202895,  0.40193059,  0.24613831],
       [ 0.38823446,  0.89940759,  0.31194782],
       [ 0.11151971,  0.39814435,  0.45873757]])

In [15]:
np.random.randn(5)

array([-0.56448005, -0.98454065,  1.18669192, -1.23025302,  0.38636658])

In [16]:
np.random.randn(5,3)

array([[ 1.37056087, -1.9196252 , -1.02401703],
       [ 1.27660527, -0.43223284,  1.00609875],
       [-0.22043653, -0.21005536,  0.29231238],
       [-0.46460115,  1.64047691, -0.1924554 ],
       [-1.54012747,  1.04468592,  0.08495576]])

In [17]:
np.random.randint(1, 100) # one random integer from 1 to 100

62

In [18]:
np.random.randint(1,100, 10) # get 10 random integers b/w 1 and 100

array([87, 96, 90, 59, 17, 47, 42, 35, 80, 85])

## Convert vector to matrix (& vice versa)

In [20]:
arr = np.arange(25)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
random_arr = np.random.randint(1,100,10)
random_arr

array([24, 60, 23, 23, 33, 69, 16, 82, 73, 79])

In [24]:
random_arr.max()

82

In [25]:
random_arr.min()

16

In [28]:
# Use `argmax` `argmin` to get the INDEX, not the value itself

random_arr.argmax()

7

In [27]:
random_arr.argmin()

6

In [29]:
# Get dimensions of array w/ `shape`

random_arr.shape

(10,)

In [30]:
arr.shape

(25,)

In [31]:
# Determine data type of an array using `dtype`

arr.dtype

dtype('int64')

In [34]:
# Copy in NumPy w/ the `copy` method

arr_copy = arr.copy()

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
arr_copy[0:11] = 8

arr_copy

array([ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
arr # notice how changing arr_copy has no effect on arr; same can't be said if done by slicing arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35,40,45]])

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [42]:
# Get 5

# Double bracket approach

arr_2d[0][0]

5

In [43]:
# Single bracket approach

arr_2d[0,0]

5

In [45]:
# Subsetting using boolean

arr = np.arange(1,11)

bool_arr = arr > 5

bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [46]:
arr[bool_arr] # subsetting, giving only output where bool is TRUE

array([ 6,  7,  8,  9, 10])

In [47]:
# Alternative approach

arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [48]:
# Method on method to create a 2d array

arr_2d = np.arange(50).reshape(5,10)

arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

Common Operations:

- `+`, `-`, `*`, `**`, etc.
- `np.sqrt(arr)`
- `np.exp(arr)`
- `np.max(arr)` or `arr.max()`
- `np.sin(arr)`, `np.cos(arr)`, `np.tan(arr)`, etc.
- `np.log(arr)`, `np.log10(arr)`, etc.

See this NumPy [documentation](https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html)or a more complete list of available functions.

In [50]:
arr = np.arange(11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])